# Horizontal Pod Autoscaler for Parlant
# Configured for MongoDB Free Tier constraints
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: parlant-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: parlant
  minReplicas: 2
  maxReplicas: 3  # Limited for Free Tier (each pod uses ~50 DB connections)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Conservative target for I/O-bound workload
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100  # Double pods if needed
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 min before scale down
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
